version: 2
jobs:
  build-java-8:
    docker:
      - image: circleci/openjdk:8-jdk


    steps:
      - checkout

      - restore_cache:
          key: >
            actordoc-v1-{{ .Branch }}
            -{{ checksum "build.sbt" }}
            -{{ checksum "project/build.properties" }}
            -{{ checksum "project/Dependencies.scala" }}
            -{{ checksum "project/Settings.scala" }}
            -{{ checksum "project/build.properties" }}
            -{{ checksum "project/plugins.sbt" }}

      - run:
          name: Run tests (with coverage)
          command: |
            sbt coverage test
            sbt coverageReport coverageAggregate

      - run:
          name: Build application
          command: |
            sbt assembly

      - save_cache:
          key: >
            actordoc-v1-{{ .Branch }}
            -{{ checksum "build.sbt" }}
            -{{ checksum "project/build.properties" }}
            -{{ checksum "project/Dependencies.scala" }}
            -{{ checksum "project/Settings.scala" }}
            -{{ checksum "project/build.properties" }}
            -{{ checksum "project/plugins.sbt" }}
          paths:
            - ~/.sbt
            - ./.ivy2/cache
        
      - store_test_results:
          path: "./actordoc-core/target/test-reports/"
      - store_artifacts:
          destination: "test-reports/unit-test"
          path: "./actordoc-core/target/test-reports/"

  quality-analysis:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout

      - run:
          name: Install Sonar Scanner
          command: |
            mkdir -p ~/tools
            pushd ~/tools
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
            unzip -qo sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
            popd
          environment:
            SONAR_SCANNER_VERSION: 4.0.0.1744

      - run:
          name: Run code analysis
          environment:
            SBT_OPTS: -Xms512m -Xmx3G
          command: |
            sbt coverageReport scapegoat
            SONAR_SCANNER_HOME=~/tools/sonar-scanner-$SONAR_SCANNER_VERSION-linux sbt -Dsonar.login=$SONAR_LOGIN sonarScan
          environment:
            SONAR_SCANNER_VERSION: 4.0.0.1744

workflows:
  version: 2
  build:
    jobs:
      - build-java-8
      - quality-analysis
  nightly:
    triggers:
      - schedule:
          cron: "14 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-java-8
      - quality-analysis
