version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk


    steps:
      - checkout

      - restore_cache:
          key: >
            actordoc-v1-{{ .Branch }}
            -{{ checksum "build.sbt" }}
            -{{ checksum "project/build.properties" }}
            -{{ checksum "project/Dependencies.scala" }}
            -{{ checksum "project/Settings.scala" }}
            -{{ checksum "project/build.properties" }}
            -{{ checksum "project/plugins.sbt" }}

      - run:
          name: Run tests (with coverage)
          command: |
            sbt coverage test
            sbt coverageReport coverageAggregate

      - run:
          name: Build application
          command: |
            sbt assembly

      - save_cache:
          key: >
            actordoc-v1-{{ .Branch }}
            -{{ checksum "build.sbt" }}
            -{{ checksum "project/build.properties" }}
            -{{ checksum "project/Dependencies.scala" }}
            -{{ checksum "project/Settings.scala" }}
            -{{ checksum "project/build.properties" }}
            -{{ checksum "project/plugins.sbt" }}
          paths:
            - ~/.sbt
            - ./.ivy2/cache
